plugins {
    id 'org.springframework.boot' version '3.4.4'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'java'
    id 'info.solidsoft.pitest' version '1.15.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'
sourceCompatibility = '17'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mockito:mockito-core'
}

pitest {
    targetClasses = ['com.example.spring_with_react.*']
    targetTests = ['com.example.spring_with_react.*']
    junit5PluginVersion = '1.2.0'
    coverageThreshold = 0 //TODO increase to 95 as we add junits
    outputFormats = ['HTML']
    timestampedReports = false
    verbose = true
    // Use all available processors
    threads = Runtime.runtime.availableProcessors()
    jvmArgs = ['-Xms512m', '-Xmx3g']
}

test {
    useJUnitPlatform()
}

tasks.named("build") {
    dependsOn("pitest")
}

